# Generated by Django 3.0.4 on 2020-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='default', max_length=254),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='counter',
            name='awards',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='counter',
            name='clients',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='counter',
            name='item_sold',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='counter',
            name='projects',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news1',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news1_autor',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news1_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news1_link',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news2',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news2_autor',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news2_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='latesttech',
            name='news2_link',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email_news',
            field=models.EmailField(default='default', max_length=254),
        ),
    ]
