# Generated by Django 3.0.4 on 2020-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20200314_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latesttech',
            name='news1_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='latesttech',
            name='news2_date',
            field=models.DateField(null=True),
        ),
    ]
