# Generated by Django 3.0.4 on 2020-03-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_auto_20200314_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latesttech',
            old_name='news1',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='latesttech',
            old_name='news1_autor',
            new_name='news_autor',
        ),
        migrations.RenameField(
            model_name='latesttech',
            old_name='news1_date',
            new_name='news_date',
        ),
        migrations.RenameField(
            model_name='latesttech',
            old_name='news1_link',
            new_name='news_link',
        ),
        migrations.RemoveField(
            model_name='latesttech',
            name='news2',
        ),
        migrations.RemoveField(
            model_name='latesttech',
            name='news2_autor',
        ),
        migrations.RemoveField(
            model_name='latesttech',
            name='news2_date',
        ),
        migrations.RemoveField(
            model_name='latesttech',
            name='news2_link',
        ),
    ]
